//! `ks secrets ...` — sops-based secrets management for the config repo.
//!
//! Secrets live in-repo under `secrets/` as sops-encrypted YAML files.
//! `.sops.yaml` at the repo root is generated (never hand-edited) from two
//! inputs:
//!
//! 1. `hosts.nix` — each host's `hostPublicKey` (ssh-ed25519) is converted
//!    to an age recipient via `ssh-to-age`.
//! 2. `secrets/recipients.nix` — admin recipients (age/yubikey identities or
//!    ssh-ed25519 user keys) plus per-file host lists for non-per-host files.
//!
//! Every creation rule gets all admin recipients. `secrets/<host>.yaml`
//! additionally gets that host's recipient; entries in `recipients.nix`
//! `files` add host lists for shared/service files.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use anyhow::{anyhow, bail, Context, Result};
use clap::Subcommand;
use serde::Deserialize;
use tokio::process::Command;

use crate::repo;

#[derive(Subcommand)]
pub enum SecretsCommand {
    /// Edit a sops-encrypted file (uses the YubiKey age identity when present).
    Edit {
        /// File to edit, relative to the current directory or the repo root.
        file: PathBuf,
    },

    /// Regenerate .sops.yaml, then re-encrypt every sops file under secrets/
    /// for the current recipient set (`sops updatekeys`).
    Rekey,

    /// Regenerate .sops.yaml from hosts.nix and secrets/recipients.nix.
    Sync,

    /// Issue short-TTL credentials (runbook only — not implemented).
    Issue,

    /// Apply sops-encrypted k8s manifests (runbook only — not implemented).
    Apply,
}

pub async fn execute(cmd: SecretsCommand, flake: Option<&Path>) -> Result<()> {
    match cmd {
        SecretsCommand::Edit { file } => edit(&file, flake).await,
        SecretsCommand::Rekey => rekey(flake).await,
        SecretsCommand::Sync => sync(flake).await,
        SecretsCommand::Issue => stub("issue", "issued-credential runbooks"),
        SecretsCommand::Apply => stub("apply", "the k8s apply runbook"),
    }
}

fn stub(name: &str, runbook: &str) -> Result<()> {
    bail!(
        "`ks secrets {}` is not implemented yet — see docs/SECRETS.md for {}.",
        name,
        runbook
    )
}

// ---------------------------------------------------------------------------
// edit
// ---------------------------------------------------------------------------

/// Path (under $HOME) of the age-plugin-yubikey identity file written by
/// `keystone.terminal.ageYubikey`.
const YUBIKEY_IDENTITY_RELATIVE: &str = ".age/yubikey-identity.txt";

/// Prefer the YubiKey age identity for sops when the caller has not already
/// chosen one: set SOPS_AGE_KEY_FILE to ~/.age/yubikey-identity.txt when the
/// env var is unset and the file exists. Shared by `edit` and `rekey` so the
/// two paths cannot drift.
fn inject_yubikey_identity(cmd: &mut Command) {
    if std::env::var_os("SOPS_AGE_KEY_FILE").is_none() {
        if let Some(identity) = home::home_dir().map(|home| home.join(YUBIKEY_IDENTITY_RELATIVE)) {
            if identity.is_file() {
                cmd.env("SOPS_AGE_KEY_FILE", &identity);
            }
        }
    }
}

async fn edit(file: &Path, flake: Option<&Path>) -> Result<()> {
    let repo_root = repo::find_repo(flake)?;
    let target = if file.exists() {
        // Absolute, since sops runs with current_dir at the repo root below.
        std::fs::canonicalize(file)
            .with_context(|| format!("Failed to resolve {}", file.display()))?
    } else {
        let in_repo = repo_root.join(file);
        if in_repo.exists() {
            in_repo
        } else if file
            .strip_prefix(&repo_root)
            .unwrap_or(file)
            .starts_with("secrets")
        {
            // New file under secrets/: let sops create it via the .sops.yaml
            // creation rules (run from the repo root so path_regex matches).
            in_repo
        } else {
            bail!(
                "File not found: {} (also tried {}; new files can only be created under secrets/)",
                file.display(),
                in_repo.display()
            );
        }
    };

    let mut cmd = Command::new("sops");
    cmd.arg(&target);
    cmd.current_dir(&repo_root);
    inject_yubikey_identity(&mut cmd);

    let status = cmd
        .status()
        .await
        .context("Failed to run sops — is it installed?")?;
    if !status.success() {
        std::process::exit(status.code().unwrap_or(1));
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// sync
// ---------------------------------------------------------------------------

const SOPS_YAML_HEADER: &str = "# GENERATED by 'ks secrets sync' — do not edit by hand.";

#[derive(Debug, Deserialize)]
struct Recipients {
    /// Admin recipients: age/yubikey identities used verbatim, ssh-ed25519
    /// entries converted via ssh-to-age.
    admins: BTreeMap<String, String>,
    /// path_regex → host list for non-per-host files.
    #[serde(default)]
    files: BTreeMap<String, FileRecipients>,
}

#[derive(Debug, Deserialize)]
struct FileRecipients {
    hosts: Vec<String>,
}

#[derive(Debug)]
struct CreationRule {
    path_regex: String,
    age: Vec<String>,
}

async fn nix_eval_file(path: &Path) -> Result<serde_json::Value> {
    let output = Command::new("nix")
        .args(["eval", "--json", "--file"])
        .arg(path)
        .output()
        .await
        .with_context(|| format!("Failed to evaluate {}", path.display()))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        bail!("Failed to evaluate {}: {}", path.display(), stderr.trim());
    }

    serde_json::from_slice(&output.stdout)
        .with_context(|| format!("Failed to parse output of nix eval {}", path.display()))
}

/// Convert an ssh-ed25519 public key to an age recipient via `ssh-to-age`.
async fn ssh_to_age(public_key: &str) -> Result<String> {
    use tokio::io::AsyncWriteExt;

    let mut child = Command::new("ssh-to-age")
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .context("Failed to run ssh-to-age — is it installed?")?;

    child
        .stdin
        .take()
        .expect("stdin was piped")
        .write_all(format!("{}\n", public_key).as_bytes())
        .await
        .context("Failed to write to ssh-to-age stdin")?;

    let output = child
        .wait_with_output()
        .await
        .context("Failed to wait for ssh-to-age")?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        bail!("ssh-to-age failed for '{}': {}", public_key, stderr.trim());
    }

    let recipient = String::from_utf8_lossy(&output.stdout).trim().to_string();
    if !recipient.starts_with("age1") {
        bail!(
            "ssh-to-age produced unexpected output for '{}': {}",
            public_key,
            recipient
        );
    }
    Ok(recipient)
}

/// Resolve a recipients.nix admin entry to an age recipient. `age1...`
/// entries (including age-plugin-yubikey recipients) pass through verbatim.
async fn admin_recipient(name: &str, value: &str) -> Result<String> {
    if value.starts_with("age1") {
        Ok(value.to_string())
    } else if value.starts_with("ssh-ed25519 ") {
        ssh_to_age(value).await
    } else {
        bail!(
            "Unsupported admin recipient '{}' in secrets/recipients.nix: expected an age1... or ssh-ed25519 value",
            name
        )
    }
}

fn escape_regex_literal(value: &str) -> String {
    value.replace('.', "\\.")
}

/// Read `hostPublicKey` per host from hosts.nix and convert to age recipients.
async fn host_age_recipients(hosts_nix: &Path) -> Result<BTreeMap<String, String>> {
    let hosts = nix_eval_file(hosts_nix).await?;
    let hosts = hosts
        .as_object()
        .ok_or_else(|| anyhow!("hosts.nix did not evaluate to an attrset"))?;

    let mut recipients = BTreeMap::new();
    for (host, info) in hosts {
        let Some(public_key) = info
            .get("hostPublicKey")
            .and_then(|value| value.as_str())
            .filter(|value| !value.is_empty())
        else {
            continue;
        };
        recipients.insert(host.clone(), ssh_to_age(public_key).await?);
    }
    Ok(recipients)
}

/// Group index for creation-rule ordering: per-host files alphabetically,
/// then services, then shared (everything else).
fn file_group(path_regex: &str) -> u8 {
    if path_regex.starts_with("secrets/services/") {
        0
    } else {
        1
    }
}

async fn build_creation_rules(repo_root: &Path) -> Result<Vec<CreationRule>> {
    let hosts_nix = repo_root.join("hosts.nix");
    if !hosts_nix.is_file() {
        bail!(
            "ks secrets sync requires hosts.nix at the repo root ({})",
            repo_root.display()
        );
    }
    let recipients_nix = repo_root.join("secrets/recipients.nix");
    if !recipients_nix.is_file() {
        bail!(
            "ks secrets sync requires secrets/recipients.nix ({})",
            recipients_nix.display()
        );
    }

    let host_recipients = host_age_recipients(&hosts_nix).await?;
    let recipients: Recipients = serde_json::from_value(nix_eval_file(&recipients_nix).await?)
        .context(
            "Unexpected shape in secrets/recipients.nix (want { admins; files.<regex>.hosts; })",
        )?;

    let mut admin_recipients = Vec::with_capacity(recipients.admins.len());
    for (name, value) in &recipients.admins {
        admin_recipients.push(admin_recipient(name, value).await?);
    }

    let host_recipient = |host: &str| -> Result<String> {
        host_recipients.get(host).cloned().ok_or_else(|| {
            anyhow!(
                "Host '{}' referenced in secrets/recipients.nix has no hostPublicKey in hosts.nix",
                host
            )
        })
    };

    // Per-host files: every host with a hostPublicKey, alphabetically.
    let mut rules = Vec::new();
    for (host, recipient) in &host_recipients {
        let mut age = admin_recipients.clone();
        age.push(recipient.clone());
        rules.push(CreationRule {
            path_regex: format!("secrets/{}\\.yaml", escape_regex_literal(host)),
            age,
        });
    }

    // files entries: services, then shared; alphabetical within each group
    // (BTreeMap iteration is already sorted by pattern).
    let mut file_rules: Vec<(u8, CreationRule)> = Vec::new();
    for (path_regex, entry) in &recipients.files {
        let mut age = admin_recipients.clone();
        for host in &entry.hosts {
            age.push(host_recipient(host)?);
        }
        file_rules.push((
            file_group(path_regex),
            CreationRule {
                path_regex: path_regex.clone(),
                age,
            },
        ));
    }
    file_rules.sort_by(|a, b| (a.0, &a.1.path_regex).cmp(&(b.0, &b.1.path_regex)));
    rules.extend(file_rules.into_iter().map(|(_, rule)| rule));

    Ok(rules)
}

fn render_sops_yaml(rules: &[CreationRule]) -> String {
    let mut out = String::new();
    out.push_str(SOPS_YAML_HEADER);
    out.push_str("\ncreation_rules:\n");
    for rule in rules {
        out.push_str(&format!("  - path_regex: {}\n", rule.path_regex));
        out.push_str(&format!("    age: {}\n", rule.age.join(",")));
    }
    out
}

async fn sync(flake: Option<&Path>) -> Result<()> {
    let repo_root = repo::find_repo(flake)?;
    let rules = build_creation_rules(&repo_root).await?;
    let sops_yaml = repo_root.join(".sops.yaml");
    tokio::fs::write(&sops_yaml, render_sops_yaml(&rules))
        .await
        .with_context(|| format!("Failed to write {}", sops_yaml.display()))?;
    println!(
        "Wrote {} ({} creation rules)",
        sops_yaml.display(),
        rules.len()
    );
    Ok(())
}

// ---------------------------------------------------------------------------
// rekey
// ---------------------------------------------------------------------------

/// A file is a sops file if it carries sops metadata (the `mac` entry inside
/// the `sops` section). Cheap content heuristic — avoids parsing every
/// format sops supports.
fn is_sops_file(content: &str) -> bool {
    content.contains("sops") && (content.contains("mac:") || content.contains("\"mac\""))
}

fn collect_sops_files(dir: &Path, files: &mut Vec<PathBuf>) -> Result<()> {
    let mut entries: Vec<_> = std::fs::read_dir(dir)
        .with_context(|| format!("Failed to read {}", dir.display()))?
        .collect::<std::io::Result<_>>()?;
    entries.sort_by_key(|entry| entry.file_name());

    for entry in entries {
        let path = entry.path();
        if path.is_dir() {
            collect_sops_files(&path, files)?;
        } else if let Ok(content) = std::fs::read_to_string(&path) {
            if is_sops_file(&content) {
                files.push(path);
            }
        }
    }
    Ok(())
}

async fn rekey(flake: Option<&Path>) -> Result<()> {
    sync(flake).await?;

    let repo_root = repo::find_repo(flake)?;
    let secrets_dir = repo_root.join("secrets");
    if !secrets_dir.is_dir() {
        bail!("No secrets/ directory at {}", repo_root.display());
    }

    let mut files = Vec::new();
    collect_sops_files(&secrets_dir, &mut files)?;
    if files.is_empty() {
        println!("No sops files found under {}", secrets_dir.display());
        return Ok(());
    }

    let mut failed = 0usize;
    for file in &files {
        println!("==> sops updatekeys {}", file.display());
        let mut cmd = Command::new("sops");
        cmd.args(["updatekeys", "--yes"])
            .arg(file)
            .current_dir(&repo_root);
        inject_yubikey_identity(&mut cmd);
        let status = cmd
            .status()
            .await
            .context("Failed to run sops — is it installed?")?;
        if !status.success() {
            eprintln!("FAIL {}", file.display());
            failed += 1;
        }
    }

    println!(
        "Rekeyed {} of {} sops files",
        files.len() - failed,
        files.len()
    );
    if failed > 0 {
        bail!("{} file(s) failed to rekey", failed);
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_generated_sops_yaml() {
        let rules = vec![
            CreationRule {
                path_regex: "secrets/maia\\.yaml".to_string(),
                age: vec!["age1admin".to_string(), "age1host".to_string()],
            },
            CreationRule {
                path_regex: "secrets/shared\\.yaml".to_string(),
                age: vec!["age1admin".to_string()],
            },
        ];

        let rendered = render_sops_yaml(&rules);
        assert_eq!(
            rendered,
            "# GENERATED by 'ks secrets sync' — do not edit by hand.\n\
             creation_rules:\n\
             \x20 - path_regex: secrets/maia\\.yaml\n\
             \x20   age: age1admin,age1host\n\
             \x20 - path_regex: secrets/shared\\.yaml\n\
             \x20   age: age1admin\n"
        );
    }

    #[test]
    fn orders_file_groups_services_then_shared() {
        assert_eq!(file_group("secrets/services/k3s\\.yaml"), 0);
        assert_eq!(file_group("secrets/shared\\.yaml"), 1);
    }

    #[test]
    fn detects_sops_metadata() {
        assert!(is_sops_file("data: ENC\nsops:\n  mac: ENC[AES256_GCM]\n"));
        assert!(is_sops_file("{\"sops\": {\"mac\": \"ENC\"}}"));
        assert!(!is_sops_file("plain: yaml\n"));
    }

    #[test]
    fn escapes_regex_dots() {
        assert_eq!(escape_regex_literal("ks.systems"), "ks\\.systems");
        assert_eq!(escape_regex_literal("maia"), "maia");
    }
}
